# docker-compose.yml
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Mapeia a porta 9090 do container para a porta 9090 da sua máquina.
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Monta o seu arquivo de configuração dentro do container.
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'